version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - db
    command: ["npm", "start"]

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DEV_DB
    ports:
      - 5432:5432
