name: CI/CD Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Cache
        uses: docker/cache-action@v2
        with:
          path: |
            /tmp/.buildx-cache

      - name: Build and start Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d --build
          sleep 10  # Wait for containers to start

      - name: Run database migrations
        run: |
          docker-compose exec -T app npx sequelize-cli db:drop
          docker-compose exec -T app npx sequelize-cli db:create
          docker-compose exec -T app npx sequelize-cli db:migrate

      - name: Run unit tests
        run: |
          docker-compose exec -T app npm test

      - name: Run integration tests
        run: |
          docker-compose exec -T app npm install cypress cypress-json-results
          docker-compose exec -T app npx cypress run

      - name: Shut down Docker containers
        run: docker-compose down
