name: CI && CD

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_DATABASE_TEST }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install dependencies
        run: npm ci

      - name: Build and start Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d --build
          sleep 10  # Wait for containers to start

      - name: Run unit tests
        run: npm test

      - name: Run database migrations
        run: |
          docker-compose exec -T app npx sequelize-cli db:drop
          docker-compose exec -T app npx sequelize-cli db:create
          docker-compose exec -T app npx sequelize-cli db:migrate

      - name: Run integration tests
        run: |
          npm install cypress cypress-json-results
          npx cypress run

      - name: Shut down Docker containers
        run: docker-compose down
